### ISSUE TITLE
Cannot save lyric files with question marks

### ISSUE THREAD

**Issue by gavinsinclair** [abhimanyuPathania/lyrico#2]
If a song title contains a question mark (?), as some song titles do, the attempt to save a lyric file fails (because a ? is not a legal file name character).

See song_helper.py lines 213 & 214

lyrics_file_name = '%s - %s.txt' % (artist, title)
lyrics_file_path = os.path.join(Config.lyrics_dir, lyrics_file_name)

Need to remove illegal characters here.

**Comment by abhimanyuPathania** [comment]
This is happens because windows does not allow "?" character in file names. But, if the file name does not contain exact 'title', then the music player won't be able to read from lyrics file. So I think it should be left the way it is. 
You can try saving lyrics in tag for that song or save lyrics manually(what I do).
